version: "3.6"

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - web:/var/www/html
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - inception
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    depends_on:
      - nginx
      - mariadb
      - redis
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: on-failure
    ports:
      - "20-21:20-21"
      - "40000-40005:40000-40005"
    networks:
      - inception
    volumes:
      - web:/home/souf
    env_file:
      - .env
  website:
    build: ./requirements/bonus/website
    image: website
    container_name: website
    restart: on-failure
    ports:
      - "40006:80"
    networks:
      - inception
  grafana:
    build: ./requirements/bonus/grafana
    image: grafana
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - inception
    volumes:
      - grafana:/etc/grafana
    env_file:
      - .env

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  web:
    driver_opts:
      type: "none"
      o: bind
      device: "/home/sel-mars/InceptionVolumes/web"
  db:
    driver_opts:
      type: "none"
      o: bind
      device: "/home/sel-mars/InceptionVolumes/db"
  grafana:
    driver_opts:
      type: "none"
      o: bind
      device: "/home/sel-mars/InceptionVolumes/grafana"