version: "3.6"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_nginx:/var/www/html
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception
    env_file:
      - .env
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - inception
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wp_nginx:/var/www/html
    env_file:
      - .env
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: on-failure
    ports:
      - "20-21:20-21"
      - "40000-40005:40000-40005"
    networks:
      - inception
    volumes:
      - wp_nginx:/home/souf
    env_file:
      - .env

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wp_nginx:
    driver_opts:
      o: bind
      device: "/Users/sel-mars/Desktop/Inception/volumes/wp_nginx"
  mariadb:
    driver_opts:
      o: bind
      device: "/Users/sel-mars/Desktop/Inception/volumes/mariadb"