apt-get update -y;
apt-get upgrade -y;
apt-get install curl apache2 php libapache2-mod-php php-curl php-cli php-mysql php-gd -y;
sed -i "s/#ServerName www.example.com/ServerName localhost/" /etc/apache2/sites-available/000-default.conf;
sed -i "s/80/8080/" /etc/apache2/sites-available/000-default.conf;
sed -i "s/80/8080/" /etc/apache2/ports.conf;
echo "ServerName localhost" >> /etc/apache2/apache2.conf;
service apache2 restart;
service apache2 stop;
rm -rf /var/www/html/index.html;
curl -Lk -o /var/www/html/index.php https://www.adminer.org/latest.php;
apachectl -D FOREGROUND;