apiVersion: 1
datasources:
- orgId: 1
  version: 2
  name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  user: $INFLUXDB_TELEGRAF_USERNAME
  database: $INFLUXDB_TELEGRAF_DBNAME
  isDefault: true
  jsonData:
    httpMode: POST
    tlsSkipVerify: true
  secureJsonData:
    password: $INFLUXDB_TELEGRAF_PASSWORD